braille: Avoid including user-provided string in printf format

diff --git a/filter/braille/drivers/index/index.sh.in b/filter/braille/drivers/index/index.sh.in
--- a/filter/braille/drivers/index/index.sh.in
+++ b/filter/braille/drivers/index/index.sh.in
@@ -1,5 +1,5 @@
 #
-# Copyright (c) 2015-2016 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (c) 2015-2016, 2018 Samuel Thibault <samuel.thibault@ens-lyon.org>
 # 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -117,7 +117,7 @@ commonOptions() {
     Bottom)      INIT+=,PN4 ;;
     BottomLeft)  INIT+=,PN5 ;;
     BottomRight) INIT+=,PN6 ;;
-    *)   echo "ERROR: unsupported $PAGENUMBER page number" >&2 ; exit 1 ;;
+    *)   printf "ERROR: unsupported %s page number\n" "$PAGENUMBER" >&2 ; exit 1 ;;
   esac
 
   echo "$INIT"
