braille: Added support for text margins.

diff --git a/filter/braille/drivers/index/index.sh.in b/filter/braille/drivers/index/index.sh.in
--- a/filter/braille/drivers/index/index.sh.in
+++ b/filter/braille/drivers/index/index.sh.in
@@ -1,5 +1,5 @@
 #
-# Copyright (c) 2015 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (c) 2015-2016 Samuel Thibault <samuel.thibault@ens-lyon.org>
 # 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -28,6 +28,7 @@ FIRMWARE=$(getOptionNumber IndexFirmwareVersion)
 FOLDING=$(getOption IndexFolding)
 TABLE=$(getOptionNumber IndexTable)
 MULTIPLEIMPACT=$(getOptionNumber IndexMultipleImpact)
+PAGENUMBER=$(getOption PageNumber)
 
 # Convert from 100th of mm to Inch fraction
 mmToIndexIn () {
@@ -71,7 +72,7 @@ mmToIndexIn () {
 commonOptions() {
   INIT=
   # Disable options we don't want: first line offset and page numbering
-  INIT+=,FO0,PN0
+  INIT+=,FO0
 
   # Support hardware-assisted multiple copies
   if [ $NB != 1 ]
@@ -82,7 +83,7 @@ commonOptions() {
   INIT+=,MI$MULTIPLEIMPACT
 
   # Support page folding
-  case $FOLDING in
+  case "$FOLDING" in
     Single)  INIT+=,DP1 ;;
     Double)  INIT+=,DP2 ;;
     SingleZ) INIT+=,DP5 ;;
@@ -101,11 +102,22 @@ commonOptions() {
     320) INIT+=,TD2 ;;
     *)   printf "ERROR: unsupported '%s' text dot distance\n" "$TEXTDOTDISTANCE" >&2 ; exit 1 ;;
   esac
-  case $GRAPHICDOTDISTANCE in
+  case "$GRAPHICDOTDISTANCE" in
     160) INIT+=,GD2 ;;
     200) INIT+=,GD0 ;;
     250) INIT+=,GD1 ;;
-    *)   printf "ERROR: unsupported '%s'graphic dot distance\n" "$GRAPHICDOTDISTANCE" >&2 ; exit 1 ;;
+    *)   printf "ERROR: unsupported '%s' graphic dot distance\n" "$GRAPHICDOTDISTANCE" >&2 ; exit 1 ;;
+  esac
+
+  case "$PAGENUMBER" in
+    None)        INIT+=,PN0 ;;
+    Top)         INIT+=,PN1 ;;
+    TopLeft)     INIT+=,PN2 ;;
+    TopRight)    INIT+=,PN3 ;;
+    Bottom)      INIT+=,PN4 ;;
+    BottomLeft)  INIT+=,PN5 ;;
+    BottomRight) INIT+=,PN6 ;;
+    *)   echo "ERROR: unsupported $PAGENUMBER page number" >&2 ; exit 1 ;;
   esac
 
   echo "$INIT"
