braille: Improvements on the braille support for bitmap images.

diff --git a/filter/braille/filters/imagetobrf.in b/filter/braille/filters/imagetobrf.in
--- a/filter/braille/filters/imagetobrf.in
+++ b/filter/braille/filters/imagetobrf.in
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright (c) 2015-2016 Samuel Thibault <samuel.thibault@ens-lyon.org>
+# Copyright (c) 2015-2017 Samuel Thibault <samuel.thibault@ens-lyon.org>
 # 
 # Permission is hereby granted, free of charge, to any person obtaining a copy
 # of this software and associated documentation files (the "Software"), to deal
@@ -56,9 +56,26 @@ esac
 
 ROTATE=$(getOption Rotate)
 case "$ROTATE" in
-  0|90|90\>|90\<|270|270\>|270\<|180) ;;
+  90\>|270\>)
+    if [ "$GRAPHICWIDTH" -gt "$GRAPHICHEIGHT" ]
+    then
+      # Landscape paper, rotate to landscape instead of to portrait
+      ROTATE=${ROTATE/\>/\<}
+    fi
+    ;;
+  0|90|270|180) ;;
   *)
     printf "ERROR: Option Rotate must be a valid rotation value, got '%s'\n" "$ROTATE" >&2
+    exit 1
+    ;;
+esac
+
+RESIZE=$(getOption Resize)
+case "$RESIZE" in
+  True) RESIZE="-size ${GRAPHICWIDTH}x${GRAPHICHEIGHT} -resize ${GRAPHICWIDTH}x${GRAPHICHEIGHT}" ;;
+  False) RESIZE="-crop ${GRAPHICWIDTH}x${GRAPHICHEIGHT}+0+0" ;;
+  *)
+    printf "ERROR: Option Resize must either True or False, got '%s'\n" "$RESIZE" >&2
     exit 1
     ;;
 esac
@@ -81,7 +98,7 @@ case $EDGE in
     ;;
 esac
 
-RENDER_CALL="convert $WORK -rotate $ROTATE -size ${GRAPHICWIDTH}x${GRAPHICHEIGHT} -resize ${GRAPHICWIDTH}x${GRAPHICHEIGHT} - $OUTPUT_FORMAT:-"
+RENDER_CALL="convert $WORK -rotate $ROTATE $RESIZE - $OUTPUT_FORMAT:-"
 
 # Now proceeed
 echo "INFO: Converting image" 1>&2
